title: Chenyu Xu's Homepage
page-top-title: Chenyu Xu
top-section-bg-text: Artificial Intelligence & communication
home-subtitle: Chenyu Xu&ensp;|&ensp;许晨宇
copyright-text: '&copy;Chenyu Xu 2023-2026. All Rights Reserved.'
